name: Sync Discovered API with APIConnect

on: [pull_request, workflow_dispatch, push]

env:
  API_HOST: mycluster-lon05-m3c-8x64-96a0e96e220543b8714ca52e486d2acc-0000.eu-gb.containers.appdomain.cloud
  PLATFORM_API_PREFIX: small-mgmt-platform-api-new-apic.mycluster-lon05-m3c-8x64-96a0e96e220543b8714ca52e486d2acc-0000.eu-gb.containers.appdomain.cloud
  PROVIDER_ORG: insurancecompany
  API_FILES: APIs/*.yaml

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Difference
        id: difference-output
        run: |
          echo "action_updates=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
      - uses: ibm-apiconnect/apic-discovery-action@main
        id: discover-apis
        with:
          api_host: ${{ env.API_HOST }}
          platform_api_prefix: ${{ env.PLATFORM_API_PREFIX }}
          provider_org: ${{ env.PROVIDER_ORG }}
          api_key: ${{ secrets.apicApikey }}
          if: env.API_FILES
          api_files: ${{ env.API_FILES }}
          else if: env.API_FOLDERS
          api_folders: ${{ env.API_FOLDERS }}
          resync_check: ${{ true }}
          git_diff: ${{ steps.difference-output.outputs.action_updates }}
      - name: Display the action-result
        run: |
          echo "Result of the action: ${{ steps.discover-apis.outputs.action-result }}"
          echo "End"